### ISSUE TITLE
Gather content for the site

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/weekend-picks-template#1]
Categorize and summarize all the events in this week's [DCist Wekend Picks](http://dcist.com/2012/05/out_and_about_weekend_picks_171.php) and turn them into markers.

**Comment by willwhite** [comment]
I have an example site set up with last week's picks. They post new one's each Friday at 1pm. 

http://tiles.mapbox.com/examples/map/map-8j8lv902

A bit interesting is that there was not much overlap in terms of categories last week, so our filtering idea isn't as useful. Do you think it still works, @aibram?

Let me know if you want any color changes.

**Comment by ansis** [comment]
Looks good to me.
