### ISSUE TITLE
App crashes on Launch

### ISSUE THREAD

**Issue by send2yaseen** [mapbox/weekend-picks-template#26]
When I tried to change the MapID as my Map ID it crashes the app.
# define kNormalMapID  @"yaseen2591.h4k49gfj"
# define kRetinaMapID  @"yaseen2591.h4k49gfj"

**Comment by incanus** [comment]
This belongs over on https://github.com/mapbox/weekend-picks-template-ios

Please post a ticket over there with a stack trace showing _where_ it crashes.
