### ISSUE TITLE
Write copy for description

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/weekend-picks-template#3]
Look at http://mapbox.com/map-sites/dc-properties/ and http://mapbox.com/map-sites/live-tweets/ for the basic idea for how these should be written. We need a short, descriptive paragraph that introduces the content of the site and explains what the site does.

**Comment by ansis** [comment]
How about this?

> There's a lot going on in Washington DC. Every weekend, the DCist has new suggestions for places to go and things to do. Explore this weekend's picks and see what's going on near you.
