### ISSUE TITLE
Fix filter interactivity

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/weekend-picks-template#4]
Right now, when I toggle a filter, the displayed markers don't change until I span or zoom on the map. 

In addition, if I toggle off a marker, pan on the map, then toggle the marker back on, the marker will be shown in it's old position from before I disabled it, then it will instantly jump to it's proper location after zooming/panning again.

**Comment by ansis** [comment]
This should now be fixed. Is it working for you now?
