### ISSUE TITLE
Add standard map site template header

### ISSUE THREAD

**Issue by willwhite** [mapbox/weekend-picks-template#8]
![](http://f.cl.ly/items/2I0H1f0Y2l3y0x291D1O/DC_s%20Changing%20Landscape%20%7C%20MapBox.png)

**Comment by ansis** [comment]
For the other templates, this doesn't seem to be in the templates themselves. Its added to the versions hosted on mapbox.com/map-sites

**Comment by willwhite** [comment]
Oh it's totally an iframe. I got pwned :)

So the task is to prepare an iframe on mapbox.com

**Comment by willwhite** [comment]
iframe is done. will push shortly.

**Comment by willwhite** [comment]
http://mapbox.com/map-sites/weekend-picks/
